version: "3"

services:
    web:
        image: nginx:1
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www:rw
            - ./conf.d:/etc/nginx/conf.d
            - ./log:/var/log/nginx
            - "phpsocket:/var/run"
        networks:
            - code-network
        depends_on:
            - php
    php:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./www:/var/www:rw
            - ./php-fpm.d:/usr/local/etc/php-fpm.d
            - ./php.ini.d:/usr/local/etc/php
            - "phpsocket:/var/run"
        networks:
            - code-network
    db:
        image: mysql:5
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: helper_dev
            MYSQL_USER: helper_dev 
            MYSQL_PASSWORD: wordpress
        ports:
            - "33060:3306"
    redis:
        image: redis:4
        ports:
            - "6379:6379"
networks:
    code-network:
        driver: bridge
volumes:
    phpsocket:
    db_data:
